//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProID { get; set; }
        public string ProName { get; set; }
        public string TinyDes { get; set; }
        public string FullDes { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int ProducerID { get; set; }
        public int Quantity { get; set; }
        public int View { get; set; }
        public string MadeIn { get; set; }
        public int CatID { get; set; }
        public Nullable<System.DateTime> ReceipDate { get; set; }
        public Nullable<int> Orders { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Comment Comment { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
